### ISSUE TITLE
How to add a new node into node created before?

### ISSUE THREAD

**Issue by AnabelCanseco** [drmad/semeele#1]
I created a UBL node and now I want to save new nodes that depends to other information computed in others method, is it possible to add more nodes?

I tried with this code based in your example using save method, but it does't work :(

```
public function crear()
	{
        $xml = new drmad\semeele\Node('ext:UBLExtension');
        $xml->child('ext:ExtensionContent')
            ->child('ds:Signature', ['Id' => 'Signature'])->save($data)
                ->child('ds:SignedInfo')


        if($this->type =='Invoice'){
            $data = $this->formato($data);
        }
            
            $data = $this->estandar($data);

		return $xml->getXML();
	}

    private function formato($s)
  
    {

       return  $s->child('ds:Reference');
    }

    private function estandar($s){


        return $s->child('control:data');

           
    }
```

**Comment by drmad** [comment]
Hi

What exactly "doesn't work"? It would be useful if you write more details, like any errors, or what you're expecting/what you're actually getting.

BTW there is a semi colon missing on line 6. Apart from that, the code should run ok. Messy, though :smile: 

Puedes comentar en español, si deseas :grin:

**Comment by AnabelCanseco** [comment]
Hola,

Lo que quiero hacer es ir concatenando nodos hijos al nodo padre, los cuales voy separando por métodos. 

ejemplo:
```
 public function crear()
	{
        $xml = new drmad\semeele\Node('libreria');
        $xml->child('libro')->save($data);

        if($this->type =='Terror'){
            $data = $this->genero($data);
        }
            
            $data = $this->descripcion($data);

		return $xml->getXML();
	}

    private function genero($s)
    {

       return  $s->add('genero','Terror')
       		->add('costo','$690')
       		->add('autor','Phill Cost');
    }

    private function descripcion($s){

        return $s->child('descripcion')
        	->add('titulo');
        	->add('edicion')
        	->add('imprenta');

    }
```

obtener: 

```
<libreria>
	<libro>
		<genero>Terror</genero>
		<costo>$690.00</costo>
		<autor>Phill Cost</autor>
		<descripcion>
			<titulo></titulo>
			<edicion></edicion>
			<imprenta></imprenta>
		</descripcion>
	</libro>
</libreria>
```

sucesivamente ir agregando nodos por método.

**Comment by drmad** [comment]
Tu código genera exactamente lo que quieres... aún no veo el problema.

Algunos detalles:

- En tu código de ejemplo, no requieres usar el método `save()`, simplemente usa `$data = $xml->child('libro');`. El método `save()` es más usado cuando quieres recordar un nodo dentro de toda una cadena de métodos, como está en el ejemplo de README.md .

- Los objetos en PHP son pasado _por referencia_ a los métodos (bueno... [casi](http://php.net/manual/en/language.oop5.references.php)), por lo que no necesitas hacer un `$data = $this->genero($data)`, simplemente `$this->genero($data)`, y dentro del método puedes obviar el `return`.
